name: FastAPI CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out the code
    - name: Check out code
      uses: actions/checkout@v3

    # 2. Set up Docker Compose
    - name: Set up Docker Compose
      uses: docker/setup-buildx-action@v2

    # 3. Start services with Docker Compose
    - name: Start services
      run: |
        docker-compose up -d
        # Wait for services to be ready
        sleep 10

    # 4. Run integration tests
    - name: Run integration tests
      run: |
        # Install additional testing dependencies
        pip install pytest requests pytest-cov
        # Run integration tests with coverage
        pytest tests/integration/ --disable-warnings --cov=server --cov-report=term-missing

    # 5. Clean up
    - name: Clean up
      run: |
        docker-compose down
      if: always()  # This ensures cleanup happens even if tests fail
